### ISSUE TITLE
DOFET 2012 file is incompatible with current field selection list

### ISSUE THREAD

**Issue by danicat** [danicat/datasus#1]
The function doesnt work with year 2012, probably because of a missing or mislabeled column. It also doesn't seem to affect any other file type. Year 2013 is not affected by this issue.

> df2 <- sim.dofet(2009)
> df2 <- sim.dofet(2012)
 Show Traceback
 
 Rerun with Debug
 Error in `[.data.frame`(df, , fields) : undefined columns selected > df2 <- sim.doext(2012)
trying URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DOFET/DOEXT12.dbc'
Content type 'unknown' length 10069943 bytes (9.6 MB)
==================================================
downloaded 9.6 MB

> df2 <- sim.domat(2012)
trying URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID10/DOFET/DOMAT12.dbc'
Content type 'unknown' length 151770 bytes (148 KB)
==================================================
downloaded 148 KB

> df3 <- sim.dofet(2013)
> head(df3[,1:2], n=1)
  death.id type
1 00421045    1

**Comment by silvadenisson** [comment]
Esse erro também está acontecendo em sim.doinf() e sim.domat(). Para evitar esse erro, tem duas soluções. A primeira é não colocar na lista variáveis as que não tem para toda série.  A outra é colocar condicionais para anos,  mas ai seria pelo menos três: em 2000, 2005, 2006.

as variáveis que precisariam sair para solução são:
'HORAOBITO'
'CODESTAB'
'NUMERODN'
'DTATESTADO'
'TPPOS'
'DTINVESTIG'
'CAUSABAS_O'
 'DTCADASTRO'
 'ATESTANTE'
  'FONTEINV'
  'DTRECEBIM'
  'CODINST'

**Comment by danicat** [comment]
Obrigada pela contribuição Denisson. Você chegou a explorar se nos arquivos que estas colunas são especificadas os dados estão preenchidos? Porque se as colunas estiverem lá, mas estiverem vazias, acredito que é seguro omitir estas colunas dos resultados para estes tipos de arquivos.

**Comment by danicat** [comment]
Adicionalmente aos campos indicados, o arquivo DOFET 2012 não possui os campos OBITOGRAV e OBITOPUERP.

**Comment by danicat** [comment]
Submetida correção temporária. Os campos inexistentes são filtrados da seleção para os tipos de arquivo DOFET, DOMAT e DOINF. Também foi adicionado um parâmetro a função `sim.load` chamado `fields` que permite maior controle sobre os campos selecionados. Este parâmetro permite o valor `'ALL'` que retorna todos os campos do arquivo original.

**Comment by silvadenisson** [comment]
ficou legal.  eu criei mais duas funções: sinasc.dn e sisprenatal. No entanto ficara um pouco diferente,  como não compreendi bem como funciona a função datasus.init() eu substituir por   localnames <- file.path(tempdir(), filenames).  Se se interessa te envio.

**Comment by danicat** [comment]
Denisson, eu gostaria de ver o seu código sim. Posso adaptá-lo para incluir no pacote. Eu vou fechar este issue já que por hora está resolvido. Você poderia abrir outro para tratarmos destas melhorias do sinasc e sisprenatal? Obrigada!
